# Generated by Django 5.0.6 on 2024-07-22 08:33

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='originalImage',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_square.jpg', force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='original'),
        ),
    ]
